### ISSUE TITLE
Folder name packages 

### ISSUE THREAD

**Issue by harikt** [crodas/Eath#2]
Is there a way that we can set another path than packages ? Some where a configuration ?

For eg: In the case of Aura, we are only keeping the Aura packages which complies to the format and with some techinque we can autoload . As this is an early release do you have something like that in mind ?

**Comment by crodas** [comment]
It would be possible, but not now. I guess it would be --dir as an argument, or packageDirectory inside the `package.yml`. I'm adding it in my todo list now.

**Comment by crodas** [comment]
Done on c2bc151a1623cd489eac5d4f1c6377b3709507bc. You can add `packageDir: <something>` in `package.yml`
